os: linux
dist: xenial
language: ruby
cache: bundler
script: "bundle exec rake test"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - head
  - rbx
gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_7_edge.gemfile
  - gemfiles/datamapper.gemfile
  - gemfiles/sequel.gemfile
jobs:
  allow_failures:
    - rvm: head
    - gemfile: gemfiles/rails_7_edge.gemfile
    - rvm: rbx
  fast_finish: false
